import fs from "node:fs";
import path from "node:path";
import { isInitialized, generatedDir } from "../config/project.js";
import { loadAllCapabilities, loadSitemap } from "../core/yaml-store.js";
import type { Capability, PageNode, Sitemap } from "../core/model.js";

/**
 * `fmap render` — generate md views from YAML into feature-map/generated/.
 * One-way, overwrite, read-only mirror. Humans edit the YAML, never this md.
 */
export async function renderCommand(): Promise<void> {
  const cwd = process.cwd();
  if (!isInitialized(cwd)) {
    console.error("No feature-map found in this project.\n  → Run `fmap init` first.");
    process.exitCode = 1;
    return;
  }
  const { byFile } = loadAllCapabilities(cwd);
  const sitemap = loadSitemap(cwd);
  const pageName = new Map(sitemap.pages.map((p) => [p.id, p.name]));

  const dir = generatedDir(cwd);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "capabilities.md"), renderCapabilities(byFile, pageName));
  fs.writeFileSync(path.join(dir, "sitemap.md"), renderSitemap(sitemap));
  fs.writeFileSync(path.join(dir, "README.md"), INDEX);

  const total = [...byFile.values()].reduce((n, list) => n + list.length, 0);
  console.log(`✓ Rendered ${total} capabilities + ${sitemap.pages.length} pages → ${path.relative(cwd, dir)}/`);
  console.log("  capabilities.md, sitemap.md (read-only mirror — edit the YAML, not these).");
}

const INDEX =
  "<!-- GENERATED by `fmap render` — do not edit. Edit the YAML in feature-map/ instead. -->\n\n" +
  "# feature-map (generated views)\n\n" +
  "- [capabilities.md](capabilities.md) — what the system can do, by module\n" +
  "- [sitemap.md](sitemap.md) — pages, tree, entity hubs\n";

const STATUS_MARK: Record<Capability["status"], string> = {
  approved: "✅ approved",
  pending: "🟡 pending",
  unknown: "❓ unknown",
  deprecated: "🚫 deprecated",
};

function cell(s: string | undefined): string {
  return (s ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function moduleName(file: string): string {
  return path.basename(file).replace(/\.(ya?ml)$/, "");
}

function renderCapabilities(byFile: Map<string, Capability[]>, pageName: Map<string, string>): string {
  const out: string[] = [
    "<!-- GENERATED by `fmap render` — do not edit. Edit the YAML in feature-map/ instead. -->",
    "",
    "# Feature Capabilities",
    "",
    "What the system can do — and where it lives. The map points; rules live in code (follow the resolvers/anchor).",
    "",
  ];
  const files = [...byFile.keys()].sort();
  if (files.length === 0) out.push("_No capabilities yet. Run `fmap build`._\n");
  for (const file of files) {
    const caps = [...byFile.get(file)!].sort((a, b) => a.id.localeCompare(b.id));
    if (!caps.length) continue;
    out.push(`## ${moduleName(file)}`, "");
    out.push("| Status | Capability | Statement | Pages | Resolvers | Anchor |");
    out.push("|---|---|---|---|---|---|");
    for (const c of caps) {
      const pages = c.mounted_on.map((id) => pageName.get(id) ?? id).join(", ") || "—";
      const resolvers = (c.resolvers ?? []).join(", ") || "—";
      out.push(
        `| ${STATUS_MARK[c.status]} | ${cell(c.name)} | ${cell(c.statement)} | ${cell(pages)} | ${cell(resolvers)} | ${cell(c.code_anchor) || "—"} |`,
      );
    }
    out.push("");
  }
  return out.join("\n");
}

function renderSitemap(sitemap: Sitemap): string {
  const out: string[] = [
    "<!-- GENERATED by `fmap render` — do not edit. Edit the YAML in feature-map/ instead. -->",
    "",
    "# Sitemap",
    "",
  ];
  if (!sitemap.pages.length) {
    out.push("_No pages yet. Run `fmap build`._\n");
    return out.join("\n");
  }

  const byId = new Map(sitemap.pages.map((p) => [p.id, p]));
  const children = new Map<string | null, PageNode[]>();
  for (const p of sitemap.pages) {
    const parent = p.parent && byId.has(p.parent) ? p.parent : null;
    (children.get(parent) ?? children.set(parent, []).get(parent)!).push(p);
  }
  const sortPages = (a: PageNode, b: PageNode) => a.name.localeCompare(b.name);

  out.push("## Pages", "");
  const walk = (parent: string | null, depth: number) => {
    for (const p of (children.get(parent) ?? []).sort(sortPages)) {
      const bits = [p.route ? `\`${p.route}\`` : "", p.entityHub ? `↳ hub for **${p.entityHub}**` : ""].filter(Boolean);
      out.push(`${"  ".repeat(depth)}- **${p.name}** ${bits.join(" ")}`.trimEnd());
      walk(p.id, depth + 1);
    }
  };
  walk(null, 0);

  const hubs = sitemap.pages.filter((p) => p.entityHub);
  if (hubs.length) {
    out.push("", "## Entity hubs", "", "_Rule: a page showing entity X can jump to X's detail._", "");
    for (const h of hubs) out.push(`- **${h.entityHub}** → ${h.name}`);
  }

  if (sitemap.transitions.length) {
    out.push("", "## Special transitions", "");
    for (const t of sitemap.transitions) {
      const from = byId.get(t.from)?.name ?? t.from;
      const to = byId.get(t.to)?.name ?? t.to;
      out.push(`- ${from} → ${to}${t.note ? ` (${t.note})` : ""}`);
    }
  }
  out.push("");
  return out.join("\n");
}
