import path from "node:path";
import fs from "node:fs";
import YAML from "yaml";
import { dirExists, fileExists, firstExistingDir, walkFiles } from "../core/fs-utils.js";

/**
 * Project-level config — committed, travels with the code so map changes ride
 * the same PR. Holds schema location, frontend root, and the tier-2 strategy
 * knobs (all defaulted). NEVER holds credentials.
 */

export const FEATURE_MAP_DIR = "feature-map";
export const CONFIG_FILENAME = "feature-map.config.yaml";

/** Whether ops-only capabilities (schema has it, frontend doesn't) are kept. */
export type OpsOnlyPolicy = "include_tagged" | "exclude";
/** "购买/续费体验卡" as one capability (coarse) or many (fine). */
export type Granularity = "coarse" | "fine";

export interface ProjectConfig {
  schema: {
    /** GraphQL endpoint URL for live introspection. */
    endpoint?: string;
    /** Header name -> ENV VAR NAME (never the literal value). */
    headers?: Record<string, string>;
    /** Path to an SDL file, relative to project root. */
    sdlPath?: string;
  };
  frontend: {
    /** Frontend source root, relative to project root. */
    root: string;
  };
  /** Tier-2 knobs — undetectable + project-dependent, every one defaulted. */
  strategy: {
    opsOnlyCapabilities: OpsOnlyPolicy;
    granularity: Granularity;
    /** Build explicit edges for arbitrary (non-entity-hub) cross-jumps? */
    specialCrossEdges: boolean;
  };
}

export function defaultProjectConfig(detected?: Partial<ProjectConfig>): ProjectConfig {
  return {
    schema: {
      sdlPath: detected?.schema?.sdlPath,
      endpoint: detected?.schema?.endpoint,
      headers: detected?.schema?.headers,
    },
    frontend: {
      root: detected?.frontend?.root ?? "src",
    },
    strategy: {
      opsOnlyCapabilities: detected?.strategy?.opsOnlyCapabilities ?? "include_tagged",
      granularity: detected?.strategy?.granularity ?? "coarse",
      specialCrossEdges: detected?.strategy?.specialCrossEdges ?? false,
    },
  };
}

export function featureMapDir(cwd = process.cwd()): string {
  return path.join(cwd, FEATURE_MAP_DIR);
}

export function capabilitiesDir(cwd = process.cwd()): string {
  return path.join(featureMapDir(cwd), "capabilities");
}

export function generatedDir(cwd = process.cwd()): string {
  return path.join(featureMapDir(cwd), "generated");
}

export function sitemapPath(cwd = process.cwd()): string {
  return path.join(featureMapDir(cwd), "sitemap.yaml");
}

export function projectConfigPath(cwd = process.cwd()): string {
  return path.join(featureMapDir(cwd), CONFIG_FILENAME);
}

export function isInitialized(cwd = process.cwd()): boolean {
  return fileExists(projectConfigPath(cwd));
}

export function readProjectConfig(cwd = process.cwd()): ProjectConfig {
  const p = projectConfigPath(cwd);
  if (!fileExists(p)) {
    throw new Error(
      `No feature-map found in this project. Run \`fmap init\` first.`,
    );
  }
  const parsed = YAML.parse(fs.readFileSync(p, "utf8")) as Partial<ProjectConfig>;
  // Merge over defaults so older/partial configs stay valid.
  return defaultProjectConfig(parsed);
}

export function writeProjectConfig(cfg: ProjectConfig, cwd = process.cwd()): void {
  fs.mkdirSync(featureMapDir(cwd), { recursive: true });
  fs.writeFileSync(projectConfigPath(cwd), renderConfigYaml(cfg));
}

/** Render config with explanatory comments — humans read & edit this file. */
function renderConfigYaml(cfg: ProjectConfig): string {
  const doc = new YAML.Document(cfg as unknown as Record<string, unknown>);
  YAML.visit(doc, {}); // no-op, keeps types happy
  const header =
    "# fmap project config — committed, travels with the code.\n" +
    "# NEVER put credentials here; the API key lives in global config / env.\n" +
    "# Set either schema.sdlPath (a local SDL file) or schema.endpoint (live\n" +
    "# introspection). For endpoint headers, give the ENV VAR NAME, not the value:\n" +
    "#   headers: { Authorization: MY_TOKEN_ENV_VAR }\n\n";
  return header + doc.toString();
}

/** Scaffold feature-map/{capabilities,generated}/ + config. Idempotent. */
export function scaffoldFeatureMap(cfg: ProjectConfig, cwd = process.cwd()): void {
  fs.mkdirSync(capabilitiesDir(cwd), { recursive: true });
  fs.mkdirSync(generatedDir(cwd), { recursive: true });
  writeProjectConfig(cfg, cwd);
  // Drop a .gitkeep so the empty capabilities dir is committable.
  const keep = path.join(capabilitiesDir(cwd), ".gitkeep");
  if (!fileExists(keep)) fs.writeFileSync(keep, "");
  // A note in generated/ so humans know not to edit it.
  const note = path.join(generatedDir(cwd), "README.md");
  if (!fileExists(note)) {
    fs.writeFileSync(
      note,
      "<!-- GENERATED by `fmap render` — do not edit. Edit the YAML in feature-map/ instead. -->\n",
    );
  }
}

// ---------------------------------------------------------------------------
// Auto-detection (tier-1): scan the repo, propose a default the user reviews.
// ---------------------------------------------------------------------------

export interface DetectionResult {
  sdlPath?: string;
  frontendRoot?: string;
  endpointGuess?: string;
}

/** Best-effort detection of schema file + frontend root, never fatal. */
export function detectProject(cwd = process.cwd()): DetectionResult {
  return {
    sdlPath: detectSdlPath(cwd),
    frontendRoot: detectFrontendRoot(cwd),
    endpointGuess: detectEndpoint(cwd),
  };
}

function detectSdlPath(cwd: string): string | undefined {
  // Prefer conventionally-named files at the root, then the largest .graphql.
  const preferred = ["schema.graphql", "schema.gql", "schema.graphqls"];
  for (const name of preferred) {
    if (fileExists(path.join(cwd, name))) return name;
  }
  const graphqlFiles = walkFiles(cwd, {
    filter: (p) => /\.(graphql|gql|graphqls)$/i.test(p),
    limit: 200,
  });
  if (graphqlFiles.length === 0) return undefined;
  // Pick the largest — most likely the full schema, not a single operation.
  let best = graphqlFiles[0];
  let bestSize = 0;
  for (const f of graphqlFiles) {
    try {
      const size = fs.statSync(f).size;
      if (size > bestSize) {
        bestSize = size;
        best = f;
      }
    } catch {
      /* ignore */
    }
  }
  return path.relative(cwd, best);
}

function detectFrontendRoot(cwd: string): string | undefined {
  // Common roots; pick the first that exists.
  const direct = firstExistingDir(cwd, ["src", "app", "frontend/src", "client/src", "web/src"]);
  if (direct) return direct;
  // Monorepo: look for packages/*/src.
  const pkgs = path.join(cwd, "packages");
  if (dirExists(pkgs)) {
    try {
      for (const e of fs.readdirSync(pkgs, { withFileTypes: true })) {
        if (e.isDirectory() && dirExists(path.join(pkgs, e.name, "src"))) {
          return path.join("packages", e.name, "src");
        }
      }
    } catch {
      /* ignore */
    }
  }
  return undefined;
}

/** Look in common GraphQL codegen configs for an endpoint URL. */
function detectEndpoint(cwd: string): string | undefined {
  const candidates = ["codegen.yml", "codegen.yaml", ".graphqlrc", ".graphqlrc.yml", ".graphqlrc.yaml"];
  for (const name of candidates) {
    const p = path.join(cwd, name);
    if (!fileExists(p)) continue;
    const text = fs.readFileSync(p, "utf8");
    const m = text.match(/https?:\/\/[^\s"'`]+/);
    if (m) return m[0];
  }
  return undefined;
}
